import UIKit

class ExersiceModel {
    
    //MARK: - Properties
    private(set) var listOfExercices: [Exercise] = []
    
    //MARK: - Private methods
    private func setUpExercices(for muscleSubgroup: MuscleSubgroup.Subgroup) {
        switch muscleSubgroup {
        case .frontDelts:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Barbell press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Military press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dumbbell front raise", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Arnold press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Cable front raise", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Cable lateral Raise", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .middleDelts:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Barbell overhead press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dumbbell Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Seated dumbbell press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dumbbell lateral raise", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Barbell upright row", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Cable upright row", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Machine Shoulder Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Machine Rear-Delt Fly", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .rearDelts:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Dumbbell back raise", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Reverse pec deck fly", comment: ""),
                                             subgroup: muscleSubgroup),]
        case .upperChest:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Incline Barbell Bench Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Incline Dumbbell Bench Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Incline Dumbbell Flye", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Smith Machine Incline Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Machine Incline Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dumbbell Pull-Over", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Low-Cable Crossover", comment: ""),
                                             subgroup: muscleSubgroup),]
        case .middleChest:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Barbell Bench Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dumbbell Bench Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dumbbell Flye", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Smith Machine Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Machine Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Pec-Deck Machine", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Pec-Deck Machine", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .lowerChest:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Decline Barbell Bench Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Decline Dumbell Bench Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Decline Dumbbell Flye", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Smith Machine Decline Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Machine Decline Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dips For Chest", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Cable Crossover", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .biceps:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Barbell Biceps Curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Standing Dumbbell Biceps Curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Standing Hummer curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Seating Hummer curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("EZ-Bar Biceps Curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Incline Dumbbell Curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Decline Dumbbell Curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Concentration Biceps Curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Overhead Cable Curl", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .triceps:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Close-grip Bench Press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Skullcrusher", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Tricep Dips", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Triceps Dip Machine", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Overhead Triceps Extension", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Cable Push-Down", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Kickbacks", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Bar Push-Down", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Diamond Push-Ups", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Bench Dip", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("One-Arm Overhead Extension", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .frontSideHip:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Barbell Squat", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Front Squat", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Leg press", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Walking Lunge", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Hack Squat", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Leg Extension", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("One Leg Extension", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Bulgarian Split Squat", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Bulgarian Split Squat", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .backSideHip:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Deadlift", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Romanian Deadlift", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Single Leg Deadlift", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Leg Curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Single Leg Curl", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Hip Thruster", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Sumo Squat", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .calves:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Machine Standing Calf Raise", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dumbbell Calf Raise", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Barbell Calf Raises", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Single Leg Calf Raise", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Donkey Calf Raises", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Seated Calf Raise Machine", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Calf Press", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .abs:
            self.listOfExercices = [Exercise(name: NSLocalizedString("High Crunches", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Bicycle Crunches", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Leg Rises", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Rised Legs Hold", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Flutter Kicks", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Scissors", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Plank", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Hanging Leg Raise", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Hanging Knee Raise Twist", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Hanging Knee Raise", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .lowBack:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Hyperextensions", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Good Morning", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Deficit Deadlift", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Bridges", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .latissimusDorsi:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Pull-ups", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Barbell Row", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Reverse-Grip Barbell Row", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Single-Arm Dumbbell Row", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Landmine Row", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dumbbell Pullover", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Single-Arm Cable Row", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Seated Low-Cable Row", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Lat Pull-down", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Reverse-Grip Lat Pull-Down", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Close-Grip Lat Pull-Down", comment: ""),
                                             subgroup: muscleSubgroup)]
        case .trapezoid:
            self.listOfExercices = [Exercise(name: NSLocalizedString("Barbell Shrug", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Barbell Behind-the-Back Shrug", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Dumbbell Shrug", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Incline Dumbbell Shrug", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Snatch-Grip Barbell High Pull", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Upright Row", comment: ""),
                                             subgroup: muscleSubgroup),
                                    Exercise(name: NSLocalizedString("Farmer's Carry", comment: ""),
                                             subgroup: muscleSubgroup)]
        }
    }
    
    //MARK: - Initialization
    init(for group: MuscleSubgroup.Subgroup) {
        self.setUpExercices(for: group)
    }
}
